### ISSUE TITLE
Setup backend tests

### ISSUE THREAD

**Issue by nchapman** [nchapman/pulsar#16]
Add tests for custom Rust code.

**Comment by ospfranco** [comment]
I've been trying to get some basic tests to run but there seems to be some issues.

1. Bun is not compatible with node, so some of the required packages to polyfill windows and whatnot are not available. The workaround, for now, seems to be using a package called happydom, which is covered by the bun documentation.
2. I'm getting some other errors afterwards, one of them [this missing variable](https://github.com/tauri-apps/tauri/issues/3434), seems the [beta version 2.0.0](https://github.com/tauri-apps/tauri/issues/3434#issuecomment-1943682845) of tauri addresses this issue, however when I try that version I run into 3.
3. It seems on the latest version they unbundled the shell API from the main package into [its own plugin]. I could integrate this into the app, however, this being beta software is probably full of its own bugs

All in all it seems both Bun and Tauri are still in very experimental phases. @nchapman let me know how you want to proceed here. I can integrate the plugin or maybe we should revert to pnpm or yarn and use tools already used by the community.

**Comment by ospfranco** [comment]
Created an issue on the Tauri repo to get some guidance as using beta versions and the amount of polyfills makes me iffy

https://github.com/tauri-apps/tauri/issues/8996

**Comment by ospfranco** [comment]
A mantainer replied on the issue I created. Seems it is not possible to right jest/buntest/vitest tests that connect with the backend. Seems the only option is really the UI test via webdriver.

Kinda dissapointing. On RN it is not possible to run e2e tests (JS to Native) headless but automation does not require any OS change.

There is one technique I use in RN though, On app start I intialize a web server that takes requests, this allows to run "commands" (RPC style) in the final app, which allows for somewhat headless testing.

**Comment by ospfranco** [comment]
I've been trying to update Tauri rust side to 2.0.0 but getting misterious errors and there is no documentation on how to achieve this.

**Comment by nchapman** [comment]
Sorry for the frustration here. I suggest that we just write separate unit tests in JS and Rust. We can mock the Tauri bridge calls on the JS side. It's not as thorough as actually doing e2e, but I think we'll end up with a more reliable and efficient test suite this way, and it's probably what we'd want anyway in addition to future integration tests using webdriver. 

This should also allow us to bypass any dom issues since we won't be testing anything via the dom itself. Also, assuming this is a workable solution, it seems like we should be able to hold off on moving to Tauri 2.0 until it's out of beta. I would love for us to be able to use bun as I think it's solving a lot of real problems in the JS ecosystem. That being said I realize it might just be too new and more trouble than it's worth. If you feel like it will save us a lot of trouble, then let's switch back to node/(npm/yarn).

How does this sound? Am I missing anything?

**Comment by ospfranco** [comment]
it seems bun is not supported in windows which means we will not be able to package the app for windows. Should I just revert to Yarn + vitest?

**Comment by nchapman** [comment]
@ospfranco Ah yeah there's the blocker we were bound to hit. Yes, let's just switch to node and yarn + vitest sounds good.
