### ISSUE TITLE
Add Rust API for file download with progress

### ISSUE THREAD

**Issue by nchapman** [nchapman/pulsar#3]
We need a Rust API that lets us download large (4GB+) model files efficiently. There's a chance we will want to use this for more than just models so it should be a general purpose API.

- [ ] Download large files efficiently using streaming
- [ ] Report progress back to the UI
- [ ] Allow the UI to specify a download location from [fs BaseDirectory enum](https://tauri.app/v1/api/js/fs).

Relevant discussion: https://github.com/tauri-apps/tauri/discussions/4726

**Comment by ospfranco** [comment]
For documentation purposes, I've been carefully reading the docs and here are some of my findings:

- Tauri bridges Rust with JS via Serde serialization, which means even though there might be some sort of IPC at play there will be some cost to send data back and forth.
- Tauri Plugins although they offer some level of encapsulation are still built upon this serialized communication. They do offer some level of per library namespace encapsulation but it's not wildly different than regular invocations. Most of the work seems to be in wrapping the bridged calls in sensible JS classes and abstractions. The [upload plugin](https://github.com/tauri-apps/tauri-plugin-upload/blob/v1/guest-js/index.ts#L47) is a good example.

In any case, I think taking the upload plugin as a base for a generic download/upload abstraction is a good starting point.

**Comment by ospfranco** [comment]
I just took deeper look into the upload plugin. It actually supports downloads with a specifiable path. So I think that takes care of this task right?

**Comment by nchapman** [comment]
@ospfranco this looks great! Yeah, looks like this plugin has what we need. I also like the idea of using this as an example of how we could develop these integrations in the future.

Since this does have the functionality we need, will you add this plugin to the project and then just write a simple wiki page on how to upload and download files (basically just a copy/paste of [your comment above](https://github.com/nchapman/pulsar/issues/3#issuecomment-1962287381))?
