### ISSUE TITLE
Yarn checksum error on tauri-watermelon

### ISSUE THREAD

**Issue by nchapman** [nchapman/pulsar#64]
Getting this error when running `yarn` on Windows: `@nozbe/watermelondb@https://github.com/ospfranco/tauri-watermelon.git#commit=1a03ebe1a7ea4052405eb3f80486d82c52e46ed4: The remote archive doesn't match the expected checksum`.

```
PS C:\Users\nchap\Code\pulsar> yarn
➤ YN0000: · Yarn 4.1.0
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed
➤ YN0000: ┌ Post-resolution validation
➤ YN0060: │ vite is listed by your project with version 5.1.5, which doesn't satisfy what vite-plugin-svgr (p66222) requests (^2.6.0 || ^3.0.0 || ^4.0.0).
➤ YN0002: │ pulsar@workspace:. doesn't provide @types/react (p8eba3), requested by react-markdown.
➤ YN0002: │ pulsar@workspace:. doesn't provide react (p3f744), requested by react-tiny-popover.
➤ YN0002: │ pulsar@workspace:. doesn't provide react (p7af64), requested by react-markdown.
➤ YN0002: │ pulsar@workspace:. doesn't provide react (pf6549), requested by effector-react.
➤ YN0002: │ pulsar@workspace:. doesn't provide react-dom (p51ef2), requested by react-tiny-popover.
➤ YN0086: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code.
➤ YN0000: └ Completed
➤ YN0000: ┌ Fetch step
➤ YN0018: │ @nozbe/watermelondb@https://github.com/ospfranco/tauri-watermelon.git#commit=1a03ebe1a7ea4052405eb3f80486d82c52e46ed4: The remote archive doesn't match the expected checksum
➤ YN0000: └ Completed in 0s 285ms
➤ YN0000: · Failed with errors in 0s 412ms
```

**Comment by ospfranco** [comment]
You might have an outdated cache affecting your machine. You can see on the CI it is building (although github seems to have connectivity issues atm):

https://github.com/nchapman/pulsar/actions/runs/8332833639/job/22802912652

You should try removing your node_modules and clearing the yarn cache and installing again (yarn cache clear)

**Comment by nchapman** [comment]
Same issue in CI at that link 🙂 

![image](https://github.com/nchapman/pulsar/assets/3095/1246a2a4-f4ca-46e3-b4d4-f467fa539509)

**Comment by ospfranco** [comment]
It seems [it's an issue with Yarn on Windows](https://github.com/yarnpkg/berry/issues/5795). I've disabled checksum verification for now, as there seems to be no other workaround. Give it another try from main.
