### ISSUE TITLE
Setup GitHub action for automatic cross platform builds

### ISSUE THREAD

**Issue by nchapman** [nchapman/pulsar#7]
Automatically build the app when merging.

- [ ] Figure out versioning plan. Semantic versioning? Add develop branch? Auto-build both?
- [ ] macOS
- [ ] Windows
- [ ] Linux

Reference: https://tauri.app/v1/guides/building/cross-platform

**Comment by ospfranco** [comment]
I have a spare mac studio that I want to try to set up as a github runner. Would it be ok to use it? I can start with this right away.

**Comment by ospfranco** [comment]
The github workflow is setup. Here is one run:

https://github.com/nchapman/pulsar/actions/runs/8081673932/job/22080785177

Right now it is failing because it has not downloaded the llamafile (it is also currently trying to import a linux arch version). Before moving forward and consuming all the minutes it would be great just to have confirmation we want this to run at this point.

**Comment by nchapman** [comment]
@ospfranco yeah totally makes sense on the missing llamafile. I was hoping we'd have a native solution ready before we automated builds, but that's going to take a bit longer. I'll just go ahead and [finish the llamafile integration](https://github.com/nchapman/pulsar/issues/8). I'll make sure we have `llamafile-x86_64-unknown-linux-gnu` handled.

I updated permissions on the board so you should be able to move the issue now. Let me know if it doesn't work!

**Comment by nchapman** [comment]
@ospfranco llamafile is now integrated in PR #33. Want to give this a try again and see if it builds via the action?

**Comment by ospfranco** [comment]
Let me give it a go

**Comment by ospfranco** [comment]
Yeah, ok. it seems only the [large Macos runners](https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/) are apple silicon. What do you think @nchapman , do you want to shell out for a larger instance?

**Comment by ospfranco** [comment]
https://github.com/oven-sh/bun/issues/43#issuecomment-1298921964

so bun doesn't officially run on Windows. There is currently experimental support, I can try to get that work but it looks like it comes with a bunch of caveats.

**Comment by nchapman** [comment]
@ospfranco yay unbuntu 🥳! I went ahead and [added a llamafile symlink for intel macs](https://github.com/nchapman/pulsar/commit/4f8b99786f896007355b4a0d56d01d9f53c782be). It does look like we can do [cross compilation](https://tauri.app/v1/guides/building/macos/#binary-targets) on macOS. So maybe the intel machine would be workable? That being said, I'm totally fine paying for a large macOS runner. Do I need to set anything up for us to do that?

**Comment by ospfranco** [comment]
Have you set up the payment on your account? the free minutes are measly anyways, so we will end up paying for more machine time anyways.

**Comment by ospfranco** [comment]
@nchapman seems we are still missing some windows arch

```
path matching bin/llamafile-x86_64-pc-windows-msvc.exe not found.
```

Can you take care of it?

**Comment by ospfranco** [comment]
Done

![Image](https://github.com/nchapman/pulsar/assets/1634213/3f945fd2-bcd6-460e-bc13-5dd2bb564bad)

it is setup to run from the `release` branch. On a simple push. We can later modify it when pushing a tag or so.
